name: .NET 5.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/ArDiCacheManager.sln
    - name: Build
      run: dotnet build  src/ArDiCacheManager.MemoryCache/ArDiCacheManager.MemoryCache.csproj --no-restore --configuration Release
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/ArDiCacheManager.MemoryCache/ArDiCacheManager.MemoryCache.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
